dubbo:
    application:
        name: user_service_provider_
    consumer:
        timeout: 3000000
    protocol:
        name: dubbo
        port: 20810
    registry:
        address: nacos://127.0.0.1:8848
mybatis:
    config-location: classpath:/mybatis-config.xml
server:
    port: 8002
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: platform
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/trading_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
        username: platform
